# Generated by Django 4.0.6 on 2022-08-01 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('name_ru', models.CharField(db_index=True, max_length=100, null=True)),
                ('name_ky', models.CharField(db_index=True, max_length=100, null=True)),
                ('name_en', models.CharField(db_index=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_ky', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('content', models.TextField()),
                ('content_ru', models.TextField(null=True)),
                ('content_ky', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/d/')),
                ('price', models.CharField(max_length=255)),
                ('price_ru', models.CharField(max_length=255, null=True)),
                ('price_ky', models.CharField(max_length=255, null=True)),
                ('price_en', models.CharField(max_length=255, null=True)),
                ('time_create', models.DateField(auto_now_add=True)),
                ('time_update', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.category')),
            ],
            options={
                'verbose_name': 'Одежда',
                'verbose_name_plural': 'Одежда',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
