# Generated by Django 4.0.6 on 2022-08-01 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ky',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='content',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='content_ky',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='time_create',
            field=models.DateField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='time_update',
            field=models.DateField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
